//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSUIR.ManagerQueue.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSUIR.ManagerQueue.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accounts Administration.
        /// </summary>
        public static string AccountsAdministrationTabName {
            get {
                return ResourceManager.GetString("AccountsAdministrationTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Account.
        /// </summary>
        public static string AccountTabName {
            get {
                return ResourceManager.GetString("AccountTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        public static string AddButtonText {
            get {
                return ResourceManager.GetString("AddButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add a secretary.
        /// </summary>
        public static string AddSecretaryLabel {
            get {
                return ResourceManager.GetString("AddSecretaryLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manager Queue.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change password.
        /// </summary>
        public static string ChangePasswordButtonName {
            get {
                return ResourceManager.GetString("ChangePasswordButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose an account:.
        /// </summary>
        public static string ChooseAccountLabel {
            get {
                return ResourceManager.GetString("ChooseAccountLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Choose a queue:.
        /// </summary>
        public static string ChooseQueueLabel {
            get {
                return ResourceManager.GetString("ChooseQueueLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Confirm password.
        /// </summary>
        public static string ConfirmPasswordFieldLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to connect to the server. Please check your network connection or try again later.
        /// </summary>
        public static string ConnectionFailedExceptionMessage {
            get {
                return ResourceManager.GetString("ConnectionFailedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Current secretaries:.
        /// </summary>
        public static string CurrentSecretariesLabel {
            get {
                return ResourceManager.GetString("CurrentSecretariesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Employee.
        /// </summary>
        public static string EmployeeRoleName {
            get {
                return ResourceManager.GetString("EmployeeRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exit queue.
        /// </summary>
        public static string ExitQueueButtonText {
            get {
                return ResourceManager.GetString("ExitQueueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на First name.
        /// </summary>
        public static string FirstNameFieldLabel {
            get {
                return ResourceManager.GetString("FirstNameFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Service address is invalid. Please set the correct address in the application configuration file..
        /// </summary>
        public static string InvalidServiceUriExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidServiceUriExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Last name.
        /// </summary>
        public static string LastNameFieldLabel {
            get {
                return ResourceManager.GetString("LastNameFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Queue - {0}.
        /// </summary>
        public static string ManagedQueueTabNameTemplate {
            get {
                return ResourceManager.GetString("ManagedQueueTabNameTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manager name.
        /// </summary>
        public static string ManagerNameColumnHeader {
            get {
                return ResourceManager.GetString("ManagerNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manager.
        /// </summary>
        public static string ManagerRoleName {
            get {
                return ResourceManager.GetString("ManagerRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Manage secretaries.
        /// </summary>
        public static string ManageSecretariesWindowTitle {
            get {
                return ResourceManager.GetString("ManageSecretariesWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Middle name.
        /// </summary>
        public static string MiddleNameFieldLabel {
            get {
                return ResourceManager.GetString("MiddleNameFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Field &apos;{0}&apos; cannot be empty.
        /// </summary>
        public static string MissingFieldErrorMessageTemplate {
            get {
                return ResourceManager.GetString("MissingFieldErrorMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move down.
        /// </summary>
        public static string MoveDownButtonText {
            get {
                return ResourceManager.GetString("MoveDownButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move up.
        /// </summary>
        public static string MoveUpButtonText {
            get {
                return ResourceManager.GetString("MoveUpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на My Queue.
        /// </summary>
        public static string MyQueueTabName {
            get {
                return ResourceManager.GetString("MyQueueTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Name.
        /// </summary>
        public static string NameFieldLabel {
            get {
                return ResourceManager.GetString("NameFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Order.
        /// </summary>
        public static string OrderFieldLabel {
            get {
                return ResourceManager.GetString("OrderFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Password.
        /// </summary>
        public static string PasswordFieldLabel {
            get {
                return ResourceManager.GetString("PasswordFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Passwords do not match.
        /// </summary>
        public static string PasswordsDoNotMatchErrorMessage {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Select a position or enter a new one....
        /// </summary>
        public static string PositionComboBoxPlaceholder {
            get {
                return ResourceManager.GetString("PositionComboBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Position.
        /// </summary>
        public static string PositionFieldLabel {
            get {
                return ResourceManager.GetString("PositionFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Priority.
        /// </summary>
        public static string PriorityFieldLabel {
            get {
                return ResourceManager.GetString("PriorityFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Queues I&apos;m In.
        /// </summary>
        public static string QueueEntriesTabName {
            get {
                return ResourceManager.GetString("QueueEntriesTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Queues Administration.
        /// </summary>
        public static string QueuesAdministrationTabName {
            get {
                return ResourceManager.GetString("QueuesAdministrationTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register.
        /// </summary>
        public static string RegisterButtonText {
            get {
                return ResourceManager.GetString("RegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Don&apos;t have an account?.
        /// </summary>
        public static string RegisterLabelText {
            get {
                return ResourceManager.GetString("RegisterLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to register using the provided information.
        /// </summary>
        public static string RegistrationFailedExceptionMessage {
            get {
                return ResourceManager.GetString("RegistrationFailedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Register.
        /// </summary>
        public static string RegistrationWindowTitle {
            get {
                return ResourceManager.GetString("RegistrationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remember me.
        /// </summary>
        public static string RememberMeCheckBoxText {
            get {
                return ResourceManager.GetString("RememberMeCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        public static string RemoveButtonText {
            get {
                return ResourceManager.GetString("RemoveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Revert changes.
        /// </summary>
        public static string RevertChangesButtonName {
            get {
                return ResourceManager.GetString("RevertChangesButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save changes.
        /// </summary>
        public static string SaveChangesButtonName {
            get {
                return ResourceManager.GetString("SaveChangesButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save order.
        /// </summary>
        public static string SaveOrderButtonText {
            get {
                return ResourceManager.GetString("SaveOrderButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Secretaries.
        /// </summary>
        public static string SecretariesButtonText {
            get {
                return ResourceManager.GetString("SecretariesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Secretary.
        /// </summary>
        public static string SecretaryRoleName {
            get {
                return ResourceManager.GetString("SecretaryRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Service address not set. Please set the correct address in the application configuration file..
        /// </summary>
        public static string ServiceUriNotSetExceptionMessage {
            get {
                return ResourceManager.GetString("ServiceUriNotSetExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign in.
        /// </summary>
        public static string SignInButtonText {
            get {
                return ResourceManager.GetString("SignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to authenticate using the provided credentials.
        /// </summary>
        public static string SignInErrorExceptionMessage {
            get {
                return ResourceManager.GetString("SignInErrorExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Sign In.
        /// </summary>
        public static string SignInWindowTitle {
            get {
                return ResourceManager.GetString("SignInWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to create entity &apos;{0}&apos;.
        /// </summary>
        public static string UnableToCreateErrorMessageTemplate {
            get {
                return ResourceManager.GetString("UnableToCreateErrorMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unable to get user information.
        /// </summary>
        public static string UserFetchFailedExceptionMessage {
            get {
                return ResourceManager.GetString("UserFetchFailedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на User name.
        /// </summary>
        public static string UserNameFieldLabel {
            get {
                return ResourceManager.GetString("UserNameFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Type.
        /// </summary>
        public static string UserTypeFieldLabel {
            get {
                return ResourceManager.GetString("UserTypeFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Vice.
        /// </summary>
        public static string ViceManagerRoleName {
            get {
                return ResourceManager.GetString("ViceManagerRoleName", resourceCulture);
            }
        }
    }
}
