//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BSUIR.ManagerQueue.Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BSUIR.ManagerQueue.Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Account.
        /// </summary>
        public static string AccountTabName {
            get {
                return ResourceManager.GetString("AccountTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager Queue.
        /// </summary>
        public static string ApplicationName {
            get {
                return ResourceManager.GetString("ApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string CancelButtonText {
            get {
                return ResourceManager.GetString("CancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePasswordButtonName {
            get {
                return ResourceManager.GetString("ChangePasswordButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPasswordFieldLabel {
            get {
                return ResourceManager.GetString("ConfirmPasswordFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to the server. Please check your network connection or try again later.
        /// </summary>
        public static string ConnectionFailedExceptionMessage {
            get {
                return ResourceManager.GetString("ConnectionFailedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Employee.
        /// </summary>
        public static string EmployeeRoleName {
            get {
                return ResourceManager.GetString("EmployeeRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit queue.
        /// </summary>
        public static string ExitQueueButtonText {
            get {
                return ResourceManager.GetString("ExitQueueButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstNameFieldLabel {
            get {
                return ResourceManager.GetString("FirstNameFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service address is invalid. Please set the correct address in the application configuration file..
        /// </summary>
        public static string InvalidServiceUriExceptionMessage {
            get {
                return ResourceManager.GetString("InvalidServiceUriExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastNameFieldLabel {
            get {
                return ResourceManager.GetString("LastNameFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager name.
        /// </summary>
        public static string ManagerNameColumnHeader {
            get {
                return ResourceManager.GetString("ManagerNameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string ManagerRoleName {
            get {
                return ResourceManager.GetString("ManagerRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle name.
        /// </summary>
        public static string MiddleNameFieldLabel {
            get {
                return ResourceManager.GetString("MiddleNameFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field &apos;{0}&apos; cannot be empty.
        /// </summary>
        public static string MissingFieldErrorMessageTemplate {
            get {
                return ResourceManager.GetString("MissingFieldErrorMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move down.
        /// </summary>
        public static string MoveDownButtonText {
            get {
                return ResourceManager.GetString("MoveDownButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move up.
        /// </summary>
        public static string MoveUpButtonText {
            get {
                return ResourceManager.GetString("MoveUpButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Queue.
        /// </summary>
        public static string MyQueueTabName {
            get {
                return ResourceManager.GetString("MyQueueTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string NameFieldLabel {
            get {
                return ResourceManager.GetString("NameFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string OrderFieldLabel {
            get {
                return ResourceManager.GetString("OrderFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string PasswordFieldLabel {
            get {
                return ResourceManager.GetString("PasswordFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords do not match.
        /// </summary>
        public static string PasswordsDoNotMatchErrorMessage {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatchErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a position or enter a new one....
        /// </summary>
        public static string PositionComboBoxPlaceholder {
            get {
                return ResourceManager.GetString("PositionComboBoxPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string PositionFieldLabel {
            get {
                return ResourceManager.GetString("PositionFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string PriorityFieldLabel {
            get {
                return ResourceManager.GetString("PriorityFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queues I&apos;m In.
        /// </summary>
        public static string QueueEntriesTabName {
            get {
                return ResourceManager.GetString("QueueEntriesTabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegisterButtonText {
            get {
                return ResourceManager.GetString("RegisterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t have an account?.
        /// </summary>
        public static string RegisterLabelText {
            get {
                return ResourceManager.GetString("RegisterLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to register using the provided information.
        /// </summary>
        public static string RegistrationFailedExceptionMessage {
            get {
                return ResourceManager.GetString("RegistrationFailedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string RegistrationWindowTitle {
            get {
                return ResourceManager.GetString("RegistrationWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string RememberMeCheckBoxText {
            get {
                return ResourceManager.GetString("RememberMeCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveQueueItemButtonText {
            get {
                return ResourceManager.GetString("RemoveQueueItemButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revert changes.
        /// </summary>
        public static string RevertChangesButtonName {
            get {
                return ResourceManager.GetString("RevertChangesButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save changes.
        /// </summary>
        public static string SaveChangesButtonName {
            get {
                return ResourceManager.GetString("SaveChangesButtonName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save order.
        /// </summary>
        public static string SaveOrderButtonText {
            get {
                return ResourceManager.GetString("SaveOrderButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secretary.
        /// </summary>
        public static string SecretaryRoleName {
            get {
                return ResourceManager.GetString("SecretaryRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service address not set. Please set the correct address in the application configuration file..
        /// </summary>
        public static string ServiceUriNotSetExceptionMessage {
            get {
                return ResourceManager.GetString("ServiceUriNotSetExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        public static string SignInButtonText {
            get {
                return ResourceManager.GetString("SignInButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to authenticate using the provided credentials.
        /// </summary>
        public static string SignInErrorExceptionMessage {
            get {
                return ResourceManager.GetString("SignInErrorExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string SignInWindowTitle {
            get {
                return ResourceManager.GetString("SignInWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create entity&apos;{0}&apos;.
        /// </summary>
        public static string UnableToCreateErrorMessageTemplate {
            get {
                return ResourceManager.GetString("UnableToCreateErrorMessageTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get user information.
        /// </summary>
        public static string UserFetchFailedExceptionMessage {
            get {
                return ResourceManager.GetString("UserFetchFailedExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserNameFieldLabel {
            get {
                return ResourceManager.GetString("UserNameFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string UserTypeFieldLabel {
            get {
                return ResourceManager.GetString("UserTypeFieldLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vice.
        /// </summary>
        public static string ViceManagerRoleName {
            get {
                return ResourceManager.GetString("ViceManagerRoleName", resourceCulture);
            }
        }
    }
}
